version: '3.8'
services:
  quietspace-frontend:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: thural/quietspace:frontend
    networks:
      - monolith-network
    env_file:
      - ./.env
    ports:
      - "5000:80"

networks:
  monolith-network:
    name: monolith-network
    driver: bridge
    external: true
