/**
 * Error Codes Constants
 * 
 * Standardized error codes for consistent error handling.
 */

/**
 * Network error codes
 */
export const NETWORK_ERROR_CODES = {
    // Base network errors
    NETWORK_ERROR: 'NETWORK_ERROR',
    NETWORK_CONNECTION_ERROR: 'NETWORK_CONNECTION_ERROR',
    NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',

    // HTTP status based errors
    BAD_REQUEST_ERROR: 'BAD_REQUEST_ERROR',
    UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
    FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    METHOD_NOT_ALLOWED_ERROR: 'METHOD_NOT_ALLOWED_ERROR',
    CONFLICT_ERROR: 'CONFLICT_ERROR',
    TOO_MANY_REQUESTS_ERROR: 'TOO_MANY_REQUESTS_ERROR',

    // Server errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BAD_GATEWAY_ERROR: 'BAD_GATEWAY_ERROR',
    SERVICE_UNAVAILABLE_ERROR: 'SERVICE_UNAVAILABLE_ERROR',
    GATEWAY_TIMEOUT_ERROR: 'GATEWAY_TIMEOUT_ERROR',

    // Authentication errors
    TOKEN_REFRESH_ERROR: 'TOKEN_REFRESH_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    INVALID_CREDENTIALS_ERROR: 'INVALID_CREDENTIALS_ERROR',
    TOKEN_EXPIRED_ERROR: 'TOKEN_EXPIRED_ERROR',
    INVALID_TOKEN_ERROR: 'INVALID_TOKEN_ERROR',
    ACCOUNT_LOCKED_ERROR: 'ACCOUNT_LOCKED_ERROR',
    PERMISSION_DENIED_ERROR: 'PERMISSION_DENIED_ERROR',
    SESSION_EXPIRED_ERROR: 'SESSION_EXPIRED_ERROR',

    // CORS and security
    CORS_ERROR: 'CORS_ERROR',
    CSRF_ERROR: 'CSRF_ERROR',
    SECURITY_ERROR: 'SECURITY_ERROR'
} as const;

/**
 * Validation error codes
 */
export const VALIDATION_ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    REQUIRED_FIELD_ERROR: 'REQUIRED_FIELD_ERROR',
    INVALID_FORMAT_ERROR: 'INVALID_FORMAT_ERROR',
    RANGE_ERROR: 'RANGE_ERROR',
    LENGTH_ERROR: 'LENGTH_ERROR',
    EMAIL_FORMAT_ERROR: 'EMAIL_FORMAT_ERROR',
    PHONE_FORMAT_ERROR: 'PHONE_FORMAT_ERROR',
    URL_FORMAT_ERROR: 'URL_FORMAT_ERROR',
    DATE_FORMAT_ERROR: 'DATE_FORMAT_ERROR',
    NUMERIC_FORMAT_ERROR: 'NUMERIC_FORMAT_ERROR',
    PATTERN_MISMATCH_ERROR: 'PATTERN_MISMATCH_ERROR'
} as const;

/**
 * System error codes
 */
export const SYSTEM_ERROR_CODES = {
    SYSTEM_ERROR: 'SYSTEM_ERROR',
    MEMORY_ERROR: 'MEMORY_ERROR',
    DISK_SPACE_ERROR: 'DISK_SPACE_ERROR',
    CPU_ERROR: 'CPU_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    FILE_SYSTEM_ERROR: 'FILE_SYSTEM_ERROR',
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
    DEPENDENCY_ERROR: 'DEPENDENCY_ERROR',
    QUOTA_EXCEEDED_ERROR: 'QUOTA_EXCEEDED_ERROR',
    RESOURCE_LIMIT_ERROR: 'RESOURCE_LIMIT_ERROR',
    CONCURRENCY_ERROR: 'CONCURRENCY_ERROR',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR'
} as const;

/**
 * Application error codes
 */
export const APPLICATION_ERROR_CODES = {
    APPLICATION_ERROR: 'APPLICATION_ERROR',
    INITIALIZATION_ERROR: 'INITIALIZATION_ERROR',
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
    STATE_ERROR: 'STATE_ERROR',
    LIFECYCLE_ERROR: 'LIFECYCLE_ERROR',
    ROUTING_ERROR: 'ROUTING_ERROR',
    NAVIGATION_ERROR: 'NAVIGATION_ERROR',
    RENDER_ERROR: 'RENDER_ERROR',
    COMPONENT_ERROR: 'COMPONENT_ERROR',
    HOOK_ERROR: 'HOOK_ERROR',
    CONTEXT_ERROR: 'CONTEXT_ERROR'
} as const;

/**
 * Data error codes
 */
export const DATA_ERROR_CODES = {
    DATA_ERROR: 'DATA_ERROR',
    PARSE_ERROR: 'PARSE_ERROR',
    SERIALIZE_ERROR: 'SERIALIZE_ERROR',
    TRANSFORM_ERROR: 'TRANSFORM_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTEGRITY_ERROR: 'INTEGRITY_ERROR',
    CONSISTENCY_ERROR: 'CONSISTENCY_ERROR',
    CONFLICT_ERROR: 'CONFLICT_ERROR',
    DUPLICATE_ERROR: 'DUPLICATE_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    RELATIONSHIP_ERROR: 'RELATIONSHIP_ERROR'
} as const;

/**
 * Business logic error codes
 */
export const BUSINESS_ERROR_CODES = {
    BUSINESS_ERROR: 'BUSINESS_ERROR',
    WORKFLOW_ERROR: 'WORKFLOW_ERROR',
    POLICY_ERROR: 'POLICY_ERROR',
    CONSTRAINT_ERROR: 'CONSTRAINT_ERROR',
    RULE_VIOLATION_ERROR: 'RULE_VIOLATION_ERROR',
    PERMISSION_ERROR: 'PERMISSION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    LIMIT_EXCEEDED_ERROR: 'LIMIT_EXCEEDED_ERROR',
    QUOTA_EXCEEDED_ERROR: 'QUOTA_EXCEEDED_ERROR',
    RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
    SUBSCRIPTION_ERROR: 'SUBSCRIPTION_ERROR',
    LICENSE_ERROR: 'LICENSE_ERROR'
} as const;

/**
 * External service error codes
 */
export const EXTERNAL_SERVICE_ERROR_CODES = {
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
    API_ERROR: 'API_ERROR',
    THIRD_PARTY_ERROR: 'THIRD_PARTY_ERROR',
    WEBHOOK_ERROR: 'WEBHOOK_ERROR',
    INTEGRATION_ERROR: 'INTEGRATION_ERROR',
    SERVICE_UNAVAILABLE_ERROR: 'SERVICE_UNAVAILABLE_ERROR',
    RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
    QUOTA_EXCEEDED_ERROR: 'QUOTA_EXCEEDED_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR',
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR'
} as const;

/**
 * All error codes combined
 */
export const ERROR_CODES = {
    ...NETWORK_ERROR_CODES,
    ...VALIDATION_ERROR_CODES,
    ...SYSTEM_ERROR_CODES,
    ...APPLICATION_ERROR_CODES,
    ...DATA_ERROR_CODES,
    ...BUSINESS_ERROR_CODES,
    ...EXTERNAL_SERVICE_ERROR_CODES
} as const;

/**
 * Error code categories
 */
export const ERROR_CODE_CATEGORIES = {
    NETWORK: Object.values(NETWORK_ERROR_CODES),
    VALIDATION: Object.values(VALIDATION_ERROR_CODES),
    SYSTEM: Object.values(SYSTEM_ERROR_CODES),
    APPLICATION: Object.values(APPLICATION_ERROR_CODES),
    DATA: Object.values(DATA_ERROR_CODES),
    BUSINESS: Object.values(BUSINESS_ERROR_CODES),
    EXTERNAL_SERVICE: Object.values(EXTERNAL_SERVICE_ERROR_CODES)
} as const;

/**
 * Get error code category
 */
export function getErrorCodeCategory(errorCode: string): keyof typeof ERROR_CODE_CATEGORIES | null {
    for (const [category, codes] of Object.entries(ERROR_CODE_CATEGORIES)) {
        if ((codes as readonly string[]).includes(errorCode)) {
            return category as keyof typeof ERROR_CODE_CATEGORIES;
        }
    }
    return null;
}

/**
 * Check if error code is in category
 */
export function isErrorCodeInCategory(errorCode: string, category: keyof typeof ERROR_CODE_CATEGORIES): boolean {
    return (ERROR_CODE_CATEGORIES[category] as readonly string[]).includes(errorCode);
}

/**
 * Get all error codes for category
 */
export function getErrorCodesForCategory(category: keyof typeof ERROR_CODE_CATEGORIES): string[] {
    return ERROR_CODE_CATEGORIES[category] as string[];
}
